### ISSUE TITLE
Installing pyfluidsynth on windows

### ISSUE THREAD

**Issue by DavidPrimor** [nwhitehead/pyfluidsynth#18]
I'm trying to install pyfluidsynth on windows. I used pip install pyfluidsynth in the command prompt, but when I tried to import fluidsynth in my python code I get:

 ModuleNotFoundError: No module named 'FluidSynth'

When I tried to install FluidSynth (by using pip install fluidsynth) another binding package was install with FluidSynth 0.2 from several years ago.
Can anybody help with specific details how to install pyfluidsynth on windows and use it? 
The error:
import FluidSynth
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm 2018.3.2\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'FluidSynth'

**Comment by sztilko** [comment]
Is there any progress on this issue?
After copying the .dll files from the compiled fluidsynth directory to C:\Windows\System32 folder this is no more an issue but the next one comes up described here:
'OSError: [WinError 193] %1 is not a valid Win32 application'
https://stackoverflow.com/questions/54166861/installing-pyfluidsynth-on-windows
From this point im stuck...

**Comment by albedozero** [comment]
This sounds like you're running 64-bit Python and trying to bind to a 32-bit fluidsynth DLL. If you haven't given up on this completely by now, can you try installing 32-bit Python or recompiling fluidsynth as 64-bit?

**Comment by albedozero** [comment]
@DavidPrimor my best guess is you might have more than one Python installed and `pip` might be installing pyfluidsynth to a different python installation than the one you're trying to run your code on. Can you confirm or provide more information?

**Comment by albedozero** [comment]
@DavidPrimor to install this library from [PyPi ](https://pypi.org/project/pyFluidSynth/) you would use
```
pip install pyFluidSynth
```
The import line in your code should read
```
import fluidsynth
```
(the case matters)
