### ISSUE TITLE
problem with pyFluidSynth

### ISSUE THREAD

**Issue by RZz96** [nwhitehead/pyfluidsynth#20]
i have installed pyFluidSynth using pip but by  import pyFluidSynth give an error :ModuleNotFoundError: No module named 'pyFluidSynth'.
also if i import fluidsynth the i get the error ImportError: Couldn't find the FluidSynth library.

**Comment by ChristianRomberg** [comment]
That doesn‘t sound like a pyfluidsynth issue at all. What is the exact import? I think you got that mixed up. Try one of the examples please and report if that works.
Thanks!

**Comment by RZz96** [comment]
i tried this one and i got error : AttributeError: 'module' object has no attribute 'Synth'


import time
import fluidsynth

fs = fluidsynth.Synth()
fs.start()

sfid = fs.sfload("example.sf2")
fs.program_select(0, sfid, 0, 0)

fs.noteon(0, 60, 30)
fs.noteon(0, 67, 30)
fs.noteon(0, 76, 30)

time.sleep(1.0)

fs.noteoff(0, 60)
fs.noteoff(0, 67)
fs.noteoff(0, 76)

time.sleep(1.0)

fs.delete()

**Comment by RZz96** [comment]
Thank you for the reply :)

i tried this one and i got error : AttributeError: 'module' object has no attribute 'Synth'

import time
import fluidsynth

fs = fluidsynth.Synth()
fs.start()

sfid = fs.sfload("example.sf2")
fs.program_select(0, sfid, 0, 0)

fs.noteon(0, 60, 30)
fs.noteon(0, 67, 30)
fs.noteon(0, 76, 30)

time.sleep(1.0)

fs.noteoff(0, 60)
fs.noteoff(0, 67)
fs.noteoff(0, 76)

time.sleep(1.0)

fs.delete()

**Comment by SpotlightKid** [comment]
Don't name one of your own modules / scripts `fluidsynth.py`

**Comment by digimbyte** [comment]
I have this same issue, my script is called player.py
I have installed FluidSynth with apt install fluidsynth for debian and can run it from console directly.
Runing the py script yeilds the error Module FluidSynth not found

**Comment by albedozero** [comment]
@RZz96 and @digimbyte there is some understandable confusion because there's another, somewhat older package on PyPi called [fluidsynth](https://pypi.org/project/fluidsynth/) which is not maintained here and does not have a `Synth` object. Also, to install [pyfluidsynth](https://github.com/nwhitehead/pyfluidsynth) you would type at the command line
```
pip install pyfluidsynth
```
but to use in your code you would add at the top
```
import fluidsynth
```
