### ISSUE TITLE
Delay on Raspberry Pi. Any way to set Chorus and Buffer Sizes?

### ISSUE THREAD

**Issue by t-oster** [nwhitehead/pyfluidsynth#3]
Hi,

I am building a RaspberryPi based E-Drum with this. It is working and if I use pyfluidsynth on my Notebook, the latency is good, but if I use it one the PI, the latency is way to big (seems like a delay of 300-500ms).
here (https://raspberrypi.stackexchange.com/questions/14987/midi-keyboard-latency-with-fluidsynth) the suggestion is to fiddle with buffer sizes and turn of chorus etc. Is there any way to do this with pyfluisynth?

**Comment by albedozero** [comment]
I think the stuff added with the latest merge does what you're looking for. For example:

```python
fs = fluidsynth.Synth()
fs.setting(audio.period-size: 64)
fs.setting(audio.periods: 3)
fs.setting(synth.chorus.active: False)
fs.setting(synth.reverb.active: False)
fs.start()
```

**Comment by t-oster** [comment]
I tried the new version, unfortunateley it does not produce any sound on the banana pi. It does not throw errors and I tried both versions with exactly the same python file. The old version works, the new one not. So I cannot try if the new options reduce the latency. Fluidsynth itself (without python) works fine.
Are there other changes which I need to make?

**Comment by t-oster** [comment]
I also tried the very latest master.zip from today (i had to `pip install future` to make it work). But it still does not make any sound... the version which works has `February 13, 2015 ` as latest entry in the `CHANGELOG.md`

**Comment by t-oster** [comment]
...hmm they all do. However the working version does not have the `device` and `midi_driver` parameter in the `start` method, so I guess it may be selecting the wrong audio device? How should the correct parameter look like?

**Comment by t-oster** [comment]
Sorry for all the self commenting. I used `git bisect` (great tool) in order to narrow it down to commit 650f872c85ef1e4d8bbacde28863b92b0f0e9115. My simple test code is:
```python
import time
import fluidsynth

fs = fluidsynth.Synth(samplerate=48000,gain=0.8)
fs.start("alsa")
sfid = fs.sfload("/usr/share/sounds/sf2/FluidR3_GM.sf2", 1)
fs.program_select(0, sfid, 0, 0)

print("Midi loaded...")

notes = [44,36,38,46,45,48]
print("testing...")
for n in notes:
    fs.noteon(9, n, 100)
    fs.noteoff(9, n)
    time.sleep(0.5)
print("done")
```

This produces sound on a banana pi until commit 650f872c85ef1e4d8bbacde28863b92b0f0e9115. After that it does not throw any error and I can hear that the audio device is opened (kind of white noise), but there is no drum sound. Any idea?

**Comment by t-oster** [comment]
..also tested on my notebook. Same problem, no sound. So this is not raspberry/bananapi/arm related...

**Comment by albedozero** [comment]
This shouldn't work differently in the newer commit, but you might try specifying the hardware-layer audio device rather than letting it use the default. The `device ` parameter is passed to the audio driver, so for ALSA something like `hw:Device,0` may work. Also, it looks a bit weird to me that your code has no time delay between `noteOn` and `noteOff` events, although I can't see why that would suddenly act differently between commits either.

**Comment by t-oster** [comment]
The missing delay is normal for drum notes as far as I know. I will try the device setting. Thanks for the fast answer.

**Comment by t-oster** [comment]
Changing device to "hw:0,0" does'nt output sound either, while not throwing any error message. I am on fluidsynth 1.1.3, do I need a newer version? Is the api-version variable in the code related to fluidsynth or to pyfluidsynth? I am on Linux Mint 17 on my notebook. Can anyone confirm the problem?

**Comment by albedozero** [comment]
[Here](https://github.com/albedozero/squishbox/blob/master/squishbox.py) is a working fluidsynth wrapper I wrote that uses pyfluidsynth. Check out line 520 where fluidsynth is invoked - maybe you can compare and spot a difference that is causing the issue.

**Comment by t-oster** [comment]
Look at this line https://github.com/nwhitehead/pyfluidsynth/blob/master/fluidsynth.py#L497
it's a simple `one-tab-too-much` issue!!!

**Comment by albedozero** [comment]
That would do it! Thanks!

**Comment by t-oster** [comment]
Thank you.  After fixing #7 your suggested parameters did reduce the latency significantly.
