### ISSUE TITLE
ImportError: Couldn't find the FluidSynth library.

### ISSUE THREAD

**Issue by LeonhWolf** [nwhitehead/pyfluidsynth#30]
Hi guys,
I cloned the pyfluidsynth as a submodule into my repository. After that I followed the install instructions by running "python setup.py install". That was also completed successfully. I also downloaded [fluidsynth-2.1.6-win10-x64.zip](https://github.com/FluidSynth/fluidsynth/releases). However, when I run the code of test.test1.py I get the following error:

*Traceback (most recent call last):
  File "d:\Documents\05_programData\01_GitRepos\metronome\c_MIDIPlayback.py", line 2, in <module>
    from a_Libraries import fluidsynth
  File "d:\Documents\05_programData\01_GitRepos\metronome\a_Libraries\fluidsynth.py", line 42, in <module>
    raise ImportError("Couldn't find the FluidSynth library.")
ImportError: Couldn't find the FluidSynth library.*

I tried tracing it back following line 42 in fluidsynth.py. But since I'm pretty new to Python I lost track pretty quickly. Googling also didn't bring up anything useful.

I'd be super happy about help! And thanks for the (probably, couldn't really test it yet :D) cool library!

### software details
* Windows 10 64 bit
* Python 3.7.9 64 bit
* If you need more details tell me

**Comment by albedozero** [comment]
The script tries to figure out where fluidsynth is installed on its own, but for Windows there isn't an installer that makes this known as there is on other systems. You can either put fluidsynth.py in the same directory as where you installed Fluidsynth, or add the location of Fluidsynth to your PATH environment variable (type "edit the system environment variables" into the search bar).

**Comment by LeonhWolf** [comment]
Thanks for your rapid answer!

I added the location of Fluidsynth to my PATH environment variable *(c:\users\myuser\appdata\local\programs\python\python37\lib\site-packages)*. Additionally, I added the .egg file to my repository. But I still get the same error.
Have a look at the screenshot of my project folder below:

![image](https://user-images.githubusercontent.com/77215755/104130456-1691dd00-5371-11eb-86d6-8a37e0f35610.png)

The file at the bottom is the .egg.

Do you have any other suggestion? Am I missing something?

**Comment by albedozero** [comment]
Oops, let me clarify - I meant add the location of where you unzipped the contents of _fluidsynth-2.1.6-win10-x64.zip_ to PATH. That will allow the `find_library` function in fluidsynth.py to locate the _libfluidsynth-2.dll_ that it needs.

**Comment by LeonhWolf** [comment]
Thanks! Adding the location of the library to PATH didn't work. But copying the file *fluidsynth-2.1.6-win10-x64.bin.libfluidsynth-2.dll* solved the ImportError. 

![image](https://user-images.githubusercontent.com/77215755/104132843-206f0c80-5380-11eb-9c4c-0d251f417fb1.png)


But now I get the error:

*Traceback (most recent call last):
  File "d:\Documents\05_programData\01_GitRepos\metronome\c_MIDIPlayback.py", line 2, in <module>
    from a_Libraries import fluidsynth
  File "d:\Documents\05_programData\01_GitRepos\metronome\a_Libraries\fluidsynth.py", line 46, in <module>
    _fl = CDLL(lib)
  File "C:\Users\leonh\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found*

I tried the following bugfixes I found online:
* pip install scipy==1.4.1
* "I would guess that the expected Microsoft Visual C runtime DLL is missing from your system." [download link](https://www.microsoft.com/en-US/download/details.aspx?id=40784)

Didn't fix it.

Sorry to bother you so long. But this library seems to be the only one where you can play midi **and** change the soundfonts.

**Comment by ChristianRomberg** [comment]
No worries. Is the architecture of the library correct (32 or 64 bit?)? Are there library dependencies (other DLLs from the zip archive) which you didn't copy?

**Comment by albedozero** [comment]
It actually needs all of the DLLs included in the fluidsynth .zip, specifically
```
libfluidsynth-2.dll
libglib-2.0-0.dll
libgobject-2.0-0.dll
libgthread-2.0-0.dll
libinstpatch-2.dll
libintl-8.dll
libsndfile-1.dll
```
If you copy all those it should work. Not sure why setting your PATH environment variable isn't working, though - maybe I closed this issue prematurely. You could also try *cough* [albedozero/fluidpatcher](https://github.com/albedozero/fluidpatcher) - the setup executable in the release installs FluidSynth and sets your environment variables appropriately.

**Comment by LeonhWolf** [comment]
I tried copying all .dll files into the project folder. This worked perfectly.

Thanks for your support @albedozero and @ChristianRomberg!
