### ISSUE TITLE
Error couldn't find FluidSynth library

### ISSUE THREAD

**Issue by Dug2555** [nwhitehead/pyfluidsynth#33]
I know a thread similar to this has been posted before, but I'm lost on what I need to do and solutions from that thread have failed me.

Currently, I have installed pyFluidSynth using the "py setup.py install --user" command on my command prompt and have set up Fluidsynth as a part of my PATH. I have tried including the .dll files directly as well as the fluidsynth folder that contains the bin folder.

All I'm trying to do is run a test file I found on the internet but I can't even get it to boot without having an error. 
![Capture](https://user-images.githubusercontent.com/59838706/134456814-cf19bed9-ec33-41c4-9052-ace097fcabd1.PNG)

**Comment by albedozero** [comment]
Looks like you might be running it in some kind of IDE, which could be setting up its own virtual environment - are you sure the PATH is set correctly in the IDE? Try just copying all the dll's from the bin directory in the into the same directory as pyfluidsynth - that should work regardless of the PATH variable settings.

**Comment by HugoSandell** [comment]
You'll need to install FluidSynth 2.1.8 or earlier. They renamed the library from libfluidsynth-2.dll to libfluidsynth-3.dll in 2.2

**Comment by albedozero** [comment]
I suspect this has been fixed by c5998a58474cee05497178b3ae75ddc02024334f
