### ISSUE TITLE
AttributeError: module 'fluidsynth' has no attribute 'Synth'

### ISSUE THREAD

**Issue by enosjeba** [nwhitehead/pyfluidsynth#36]
`def display_audio(pm: pretty_midi.PrettyMIDI, seconds=30): 
  waveform = pm.fluidsynth(fs=sampling_rate)
  waveform_short = waveform[:seconds*sampling_rate] 
  return display.Audio(waveform_short, rate=sampling_rate)`

This is the Code,
I installed fluidsynth by `pip install --upgrade pyfluidsynth`

**Comment by snhobbs** [comment]
There is a package on pypi named fluidsynth that will raise that error. If you somehow installed that package you will get that error.

You can run the following to see if the other fluidsynth package is installed.
```
pip show fluidsynth
```
```
Name: fluidsynth
Version: 0.2
Summary: Fluidsynth bindings
Home-page: http://corbinsimpson.com/
Author: Corbin Simpson
Author-email: MostAwesomeDude@gmail.com
License: UNKNOWN
Location: /usr/local/lib/python3.8/dist-packages
Requires: 
Required-by: 
```
