### ISSUE TITLE
fluidsynth: error: Unknown integer parameter 'synth.sample-rate'

### ISSUE THREAD

**Issue by jakerieger** [nwhitehead/pyfluidsynth#37]
Running the sample code in the readme works but I get this error in the console. I tried supplying a sample rate to the `fluidsynth.Synth()` constructor but that didn't remove it.

**Comment by Rainbow-Dreamer** [comment]
You can the default value of samplerate in the `__init__` function of Synth class from `44100` to `44100.0`, which will fix the error.
Change line 614
```python
def __init__(self, gain=0.2, samplerate=44100, channels=256, **kwargs):
```
to
```python
def __init__(self, gain=0.2, samplerate=44100.0, channels=256, **kwargs):
```

**Comment by Rainbow-Dreamer** [comment]
You can change the default value of `samplerate` in `__init__` function of Synth class from `44100` to `44100.0`, which will fix the error.
Change line 614
```python
def __init__(self, gain=0.2, samplerate=44100, channels=256, **kwargs):
```
to
```python
def __init__(self, gain=0.2, samplerate=44100.0, channels=256, **kwargs):
```

**Comment by Fruchtzwerg94** [comment]
See #44
