### ISSUE TITLE
Can't set "audio-bufsize"

### ISSUE THREAD

**Issue by frans-fuerst** [nwhitehead/pyfluidsynth#41]
Via `fluidsynth` command line you can set the audio buffer size via `-z` or `--audio-bufsize`. For some strage reason I need to set it on Fedora 36+ to get non-chopped output.
However there seems to be no way to set this value using `Synth.settings`. Despite those look somehow generic, there was no way to set it the `setting()` function
I tried: `audio.bufsize`, `audio.buffer-size` `audio.buf-size`, `synth.bufsize`, `synth.buf-size`, `synth.audio-bufsize` and some more without success.
Is there a way to workaround this?

I'm using pyFluidSynth v1.3.1 fluidsynth v2.3.1 on Python 3.10

**Comment by frans-fuerst** [comment]
Ok, found it - was just bad naming inside `fluidsyth` itself - while the command line option is called `--audio-bufsize` the actual internal parameter is called `audio.period-size`. Setting this works for me.

**Comment by ChristianRomberg** [comment]
Hi,
just briefly looking into this, I was not able to find the audio buffer
size anywhere in the libfluidsynth docs page:
https://www.fluidsynth.org/api/settings_synth.html
Maybe there's a difference between synthesizer and audio settings?
Chris

Frans Fürst ***@***.***> schrieb am Di., 31. Jan. 2023, 18:17:
