### ISSUE TITLE
Support `fluid_synth_all_sounds_off` and `fluid_synth_all_notes_off`

### ISSUE THREAD

**Issue by kevinzakka** [nwhitehead/pyfluidsynth#42]
Hi @nwhitehead,

Would you be down to adding support for `fluid_synth_all_sounds_off` and `fluid_synth_all_notes_off`? Am happy to submit a PR if you are busy.

**Comment by kevinzakka** [comment]
CC @albedozero

**Comment by ChristianRomberg** [comment]
This sounds like a thing that would make pyfluidsynth more feature complete. I think a PR would be very handy, I could upload a new version to pypi once merged

**Comment by ChristianRomberg** [comment]
I uploaded the new version to PyPI. Thank you for your contribution!
