### ISSUE TITLE
Reverb issue

### ISSUE THREAD

**Issue by jkaramichos** [nwhitehead/pyfluidsynth#46]
When loading some .sf2 files, fluidsynth will not play a reverb - even when manually calling 'set_reverb()' with max roomsize, width, level.
Note that with certain .sf2 files, I'm getting an appropriate reverb response when changing the settings using set_reverb(). 

Looking for some assistance to fix this issue.

**Comment by albedozero** [comment]
This can happen if the soundfont has been edited or created with a reverb level of 0% at the instrument or preset level. You can use a soundfont editor (e.g. polyphone, swami) to check this and change the value if you want.

**Comment by jkaramichos** [comment]
That helped, thanks!
