### ISSUE TITLE
How to access reverb functionality

### ISSUE THREAD

**Issue by brannanz** [nwhitehead/pyfluidsynth#49]
This library is in dire need of some kind of api docs - how do I set the reverb level?? I tried set_reverb but no matter what arguments i gave it, it wouldn't work

**Comment by nwhitehead** [comment]
@brannanz Totally agree with everything you say. I had personally never tried reverb. I went through and wrote a test example for pull request #63. I managed to get it working.

One big thing I learned is that merely turning on reverb in fluidsynth is not enough to get reverb. You also have to have reverb send enabled in the SF2 file. Each preset in the SF2 can define how much signal to send to the reverb. In the example SF2 file there was (previously) no reverb set, so no matter what you do with fluidsynth reverb settings you would not hear reverb with the example SF2. I updated the SF2 to turn on reverb and got my new sample working. I used Polyphone to edit the sample SF2 file.

@brannanz Could you try the latest code in this repository and see if you can get reverb with `test/test4.py`?

**Comment by brannanz** [comment]
Will check later, thanks 😁

**Comment by nwhitehead** [comment]
Closing as inactive, feel free to re-open if you think there is still an issue.
