### ISSUE TITLE
New PyPI release

### ISSUE THREAD

**Issue by yawjalik** [nwhitehead/pyfluidsynth#50]
Hello there, could we kindly get a new release to integrate some existing changes? I'm coming from [an open issue from this repo](https://github.com/craffel/pretty-midi/issues/236) which can be fixed by integrating changes from #37. Thanks!
@ChristianRomberg

**Comment by ChristianRomberg** [comment]
I'm sorry for the slow response. I got things going on…
I'll go through the changes and upload a new version ASAP.
- Chris
