### ISSUE TITLE
Python Bindings

### ISSUE THREAD

**Issue by PeterPHanlon** [nwhitehead/pyfluidsynth#70]
I tried to make a short Python establish-an-app under Thonny on Rpi.
I really liked the Python entry into the fluid synth environment.

I was trying to link an Arduino-based app that generates MIDI note-on/off sequences into a Raspberry Pi, and use 'aconnect xx:0 yy:0' construct to get the external MIDI into fluid synth.

If I run fluid synth (2.3.5) as a standalone server, the aconnect above works well, but if I try to operate through Thonny and pyfluidsynth, I instantly get return code -11. I can't find the code documented and am asking for help before elaborating with chapter and verse.

What I am trying to do is pick up musical key strokes on an ancient electronic organ, and deliver them to an Rpi operating fluid synth. I am OK on electronics, passable on Python, very basic  on Linux.

I think the immediate future involves Python linkages, and applaud whitehead for the great job he has done,

Peter Hanlon

**Comment by nwhitehead** [comment]
@PeterPHanlon That sounds like a fun project!

I'm not sure what the -11 return code would be. One issue might be finding the fluidsynth shared library, that is a common issue on some platforms. Does that seem to be the issue based on the output?

**Comment by nwhitehead** [comment]
@PeterPHanlon I should also mention my project https://github.com/nwhitehead/tinysoundfont-pybind in case it's helpful for you. It's more of a self-contained thing which can be useful in some environments. I don't think PyPI has binaries for rpi though, so you would need to build from source package (and it includes a little bit of C++ code so it requires a compiler).

**Comment by PeterPHanlon** [comment]
Dear Nathan,

Thanks for the quick note. Very much appreciated.

If you had replied “-11 means XXX you silly bastard” I would have made instant headway!

I will try to reduce the problem and perhaps try to enable verbose stuff in fluidsynth. I am 82 and am keen to solve this before karking it.

Sincerely,

Peter

**Comment by PeterPHanlon** [comment]
I am using an Rpi 4B, and its Bookworm version which is moderately recent, and pushes users into a more controlled ‘venv’ environment. I imagine that finding libraries could be a likely issue.

I tried several functions to try out Reverb and Chorus set-up, and also the Router functionality. I didn’t have success with the Channel Info routine, but program changes seemed successful.

Peter

**Comment by cclauss** [comment]
Please provide the full error trace so we can see where in the code the error occurred.

**Comment by PeterPHanlon** [comment]
Thanks so much for your help.

I have spent about a week on this, and mea culpa, mea culpa, mea maxima culpa it was my fault.

In the course of disabling all fluidsynth unnecessary calls to pinpoint the error, I found a misplaced fs.delete() from the shutdown sequence had been unintentionally called.

I verified that it was indeed responsible for the -11 return code.

Please close the issue, and thanks again,

Peter Hanlon

**Comment by cclauss** [comment]
Nice!  Happy hacking on the Raspberry Pi.  Please let us know if you have further issues.

**Comment by PeterPHanlon** [comment]
Thanks for treating a beginner so respectfully.

I have two main problems:

(1) Passing settings parameters into fluidsynth

I researched what I could find, and settled for an approach where you build a Python dictionary of key-value pairs, and hand that to the fluidsynth constructor. 
In short  fs = fluidsynth.Synth(dict) and utilise the **kwargs feature.  Works quite successfully.  

(2) Accessing fluidsynth stdout output
I can’t find how to manage this. I have some channel routing complexities to set up, and will need the stdout to debug it. I suspect stderr is already available.
Please point me in the right direction

Peter Hanlon

**Comment by cclauss** [comment]
Sounds like you are on a good path with 1.  On 2., I tend to use [`completed_process = subprocess.run(command, text=True)`](https://docs.python.org/3/library/subprocess.html#subprocess.run), and then I can examine [`completed_process`](https://docs.python.org/3/library/subprocess.html#subprocess.CompletedProcess) variables `returncode`, `stdout`, `stderr`, etc.
