### ISSUE TITLE
No tags

### ISSUE THREAD

**Issue by therealmate** [nwhitehead/pyfluidsynth#78]
Hello, I am the maintainer of the python-pyfluidsynth (https://aur.archlinux.org/packages/python-pyfluidsynth) package in the aur. I would appreciate it if you could tag releases like other python libraries do, so I don't have to build from PyPI, which, according to https://github.com/nwhitehead/pyfluidsynth/blob/master/CHANGELOG, is out of date (1.3.3 on PyPI, 1.3.4 in the changelog) and it's also not the recommended way of downloading sources (https://rfc.archlinux.page/0020-sources-for-python-packaging/)

**Comment by cclauss** [comment]
This is a reasonable request and I will do so on our next release.

I would like to get #77 resolved first but perhaps we should not wait too long.
* #77
