### ISSUE TITLE
Publish release v1.3.4 to PyPI

### ISSUE THREAD

**Issue by cclauss** [nwhitehead/pyfluidsynth#81]
I do not have access rights to do this.
* https://pypi.org/project/pyFluidSynth
* https://github.com/nwhitehead/pyfluidsynth/releases <-- Release asset are at the bottom of this page.

**Comment by nwhitehead** [comment]
@cclauss I invited you on PyPI, let me know if that didn't work

**Comment by cclauss** [comment]
Published: https://pypi.org/project/pyFluidSynth
