### ISSUE TITLE
Some instruments are off 1 octave

### ISSUE THREAD

**Issue by bjascob** [nwhitehead/pyfluidsynth#82]
Some instruments appear to be 1 octave off in frequency from the expected value. For instance on the "Hammond Organ", midi note 60 is C3 when it should be C4. I originally noticed this when looking at STFT plots of the output which clearly show the issue. However, you can hear it too. It's easiest to hear it using a simple python test script and/or compare it to the sound from a program like VMPK. With VMPK you can manually load the same soundfont so you can be assured that it's not the font causing the issue.

Here's a sample script to demonstrate the issue. It can be difficult to hear but if you increase the sleep times and play it on top of audio from VMPK it's fairly obvious.
```
import time
import fluidsynth

fs = fluidsynth.Synth()
fs.start()
sfid = fs.sfload('/usr/share/sounds/sf2/FluidR3_GM.sf2')
# program_select(channel, soundfont_id, bank_num, program_num))
fs.program_select(0, sfid, 0, 0)    # Acoustic Grand Piano
fs.program_select(1, sfid, 0, 16)   # Hammond Organ
veloctiy = 100
midinum  = 60
if 1:
    print('Playing Hammond Organ C4')   # corresponds to C3
    fs.noteon(1, midinum, veloctiy)
    time.sleep(1.0)
    fs.noteoff(1, midinum)
if 1:
    print('Playing Acoustic Grand Piano C4')    # correct C4
    fs.noteon(0, midinum, veloctiy)
    time.sleep(1.0)
    fs.noteoff(0, midinum)
if 1:
    print('Playing Hammond Organ C5')   # corresponds to C4
    fs.noteon(1, midinum+12, veloctiy)
    time.sleep(1.0)
    fs.noteoff(1, midinum+12)
if 1:
    print('Playing Hammond Organ C6')   # corresponds to C5
    fs.noteon(1, midinum+24, veloctiy)
    time.sleep(1.0)
    fs.noteoff(1, midinum+24)
fs.delete()
```
Is this a setup issue of mine or is there something going wrong in the python bindings?

**Comment by bjascob** [comment]
After doing a little more investigating, I see that VMPK uses SonivoxEAS as the default MIDI driver and this driver outputs the correct octave for program 16 using the FluidR3_GM.sf2 soundfont.

If I switch the driver to FluidSynth and load the same soundfont, I get the same behavior seen above, so it looks like the issue is something to do the underlying library. In addition, after a little more careful scrutiny, this is the only instrument that I find that does this.

I'd be interested in any insights you have into what's going on but at this point I'm just going to chalk-it-up to some anomaly with the FluidSynth library itself.

**Comment by nwhitehead** [comment]
@bjascob It's possible there is some midi note offset/mapping setting in the soundfont that fluidsynth is not interpreting correctly. I don't think it is a problem in the python bindings in this project, more of an issue with fluidsynth itself.

I also tried Polyphone and it seemed to be the same octave as fluidsynth. I also tried `rustysynth` and it sounded the same (it is based on C# `meltysynth`).

I'm going to close this here, please re-open if you find out more details and it seems like it is a problem with the bindings here.

**Comment by cclauss** [comment]
It would be great if this issue could get reopened at https://github.com/FluidSynth/fluidsynth

**Comment by bjascob** [comment]
For reference, this issue was re-posted at https://github.com/FluidSynth/fluidsynth/issues/1443
