### ISSUE TITLE
Version 1.2.5 is not on Pypi

### ISSUE THREAD

**Issue by stefan-balke** [nwhitehead/pyfluidsynth#9]
Hey,

I just spend some hours trying to get `pyfluidsynth` running on OSX High Sierra only to find out that the PyPi version is 1.2.4.

Could you please update this to 1.2.5?

Thanks!

**Comment by stefan-balke** [comment]
Also the homepage should be pointing to this GitHub repo?

**Comment by stefan-balke** [comment]
Bugging @nwhitehead

**Comment by ChristianRomberg** [comment]
@nwhitehead [wanted to do something about the pypi thing back in march,](https://github.com/nwhitehead/pyfluidsynth/pull/8) but since then, nothing happened. Not sure if this repository is still being actively maintained.

**Comment by stefan-balke** [comment]
Maybe @bspaans may jump in and/or put you in as a maintainer on PyPi?

**Comment by bspaans** [comment]
Hi, sorry wasn't aware of this repo. Unfortunately I don't really have the bandwidth to do a release, but I'm happy to add another owner to the PyPI repo in case @nwhitehead has lost his credentials.

**Comment by ChristianRomberg** [comment]
I'd be happy to do the maintenance work. The repository really needs an
update. You can find my PyPI profile here:
https://pypi.org/user/ChristianRomberg/

Bart Spaans <notifications@github.com> schrieb am Mo., 16. Juli 2018, 18:59:

**Comment by nwhitehead** [comment]
Congratulations, Christian, you're a project co-owner! Go for it. I did a quick release command or two but got failures, stuff about the setup.py requirements, then missing targets. Haven't done it for years, needs some love.

**Comment by stefan-balke** [comment]
@nwhitehead, @bspaans thanks for your work!

@ChristianRomberg congrats! If you need any help, let me know!

**Comment by ChristianRomberg** [comment]
Ok, just updated the version on pypi. Forgot to upload my changes to this repo, will do that later.
